### ISSUE TITLE
Connecting pi to flight controller

### ISSUE THREAD

**Issue by nicholaskgeorge** [CornellAerialRobotics/cu-arc-19-20#16]
Currently we are looking in the use a library called Drone kit in order to achieve this. We are still working out the issues.

**Comment by rpappa** [comment]
We're going to use serial communication and have the Pi act as the receiver

**Comment by nicholaskgeorge** [comment]
The pi can now send the correct pitch, yaw, throttle and roll values to the flight controller. Issue was solved by using the IBUS protocol and having the pi act as a receiver.
